- agency/python/src/reputation_calculation.py
- agency/python/src/reputation_calculation_statistics.py
- agency/python/src/reputation_service_api.py
> reputation service API

- agency/python/src/reputation_calculation.py
- agency/python/src/reputation_service_api.py
- agency/python/src/test_reputation.py
- agency/python/src/test_reputation_service_api.py
> Some updates on Python API

- agency/python/src/reputation_calculation.py
- agency/python/src/reputation_service_api.py
- agency/python/src/test_performance.py
Test result:
Time spent: 2577.779157400131 seconds (cca 45 minutes).
> Performance test

- agency/python/src/reputation_calculation.py
Fix on the performance test issue.
I managed to reproduce the error @akolonin mentioned and resolved it. I tested and did not get the same error anymore (after this fix). However, now the script runs several tests and it works quite slow on local machine, so they are not completed yet. I am also running them on server, so far (an hour or so in), all seems ok.
> Fix on the performance test issue

- .gitignore
- README.md
- resources/linuxbuild/Dockerfile
- resources/linuxbuild/README.md
- scripts/docker-build
- scripts/docker-clean
- scripts/docker-run
- setup.py
With this change, I add instructions on map the loclatest.com host to localhost needed by Aigents Java server.
I map that port automatically if using docker for development
Closes #149
> dependencies in setup.py and Java in docker

- reputation/reputation_base_api.py
- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
test_unrated passing besides other fixes I did before. The biggest mention (that I did mention before) is that now I included assertDictEqual, so test_reputation is changed because of that.
> test_unrated passing

- reputation/issue1.tsv
- reputation/reputation_calculation.py
- reputation/test_reputation.py
Added unittest + 185 issue fix. Also added all the data needed for the next unittest - we need tsv stored data in order to test rs on more transactions.
> Added unittest + 185 issue fix

- reputation/test_reputation.py
Fix on #192
Now unittests pass also for put_ratings function.
> Fix on #192

- reputation/test_reputation.py
Running all tests in both Java and Python
> Running all tests in both Java and Python

- reputation/reputation_service_api.py
- reputation/test_reputation.py
- reputation/testdata/problematic_transactions2.csv
Roundings are fixed, however not all deviations are fixed with this. Also, new unittests have been made.
> Fixed roundings

- reputation/reputation_calculation.py
- reputation/test_reputation.py
> More fixes for #135

- reputation/reputation_scenario.py
- reputation/reputation_service_api.py
Printouts fixed. @akolonin I hope this works the same on your machine. I tried on server and at the beginning I did not get some of the printouts and I removed the rest that I did get. So, I am not 100% sure if this will work the same on your machine.
> Printouts fixed

- reputation/reputation_calculation.py
Rounding fix
This fix is nothing new, it just assures more stable rounding. The existing flea-sized deviation is further reduced with this one, so it is an improvement.
> Rounding fix

- reputation/reputation_calculation.py
- reputation/test_reputation.py
Downratings fix. I also added a new unittest to make sure that we indeed scale on 0 to 1. Furthermore, if there is 1 or more downratings that are higher than 1, then Python raises value error.
> Downratings fix

- reputation/reputation_calculation.py
- reputation/test_reputation.py
reputation_calculation documentation.
> reputation_calculation documentation

- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
rater_bias implemented together with unittest
> rater_bias implemented together with unittest

- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
Not sure if everything is 100% correct because I did not compare it to Java version. Results however make sense when glancing through the numbers. I added also a unittest that is only checked by Python so far.
Regarding the fix of #250, I submitted the code from last time again ( #258 - so previous pull request is included in this one). I would say we merge it, it is just one line of code and then if it does not work I can uncomment it anyway and we are back to the state we were in before my fix on issue #250 .
> Predictiveness implemented

- reputation/reputation_service_api.py
Note: unfortunately I have port issues again and was not able to check unittests. It's just one line of code, so it should be fine.
This time those issues came from my side since I was playing a lot with different port configurations for a related issue. I will fix them at some point, probably next week.
> quick fix of #250

- reputation/reputation_buying_test.py
Comparing metrics for Java-based and Python-based Anti-biased RS
> Comparing metrics for Java-based and Python-based Anti-biased RS

- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
Issue with test_predictiveness and test_predictiveness_v2. I am still working on it. So, note the code on predictiveness is still a work in progress and is not working properly yet (in Python that is).
> Current work on predictiveness

- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
- reputation/test_reputation_service_api.py
- reputation/test_reputation_simulation.py
This is another pull that builds on previous one (which has not been accepted yet). Here I am changing the imports in several files and making them work in a way I believe Artur suggested. Also, I got rid of numpys and pandas in test_reputation, though for one case I only commented the code I replace (and replaced it) instead of deleting it. I believe there pandas and numpys are used by design, so it does not make such big sense in changing that. Nevertheless, unittests are passing...
> Further code improvements

- reputation/reputation_calculation.py
- reputation/reputation_service_api.py
- reputation/test_reputation.py
> Predictiveness fix
